- hosts: all,!localhost
  gather_facts: "{{ get_facts }}"
  tasks:
    - name: display repo_count
      debug:
        var: repo_count
        
    - name: Execute User Defined Command
      shell: "{{ command }}"
